const fs = require('fs');
let html = fs.readFileSync('index.html', 'utf8');

const replacements = [
  { line: 53, old: "border- ", new: "border-navy " },
  { line: 183, old: "border- ", new: "border-line " },
  { line: 198, old: "text- ", new: "text-gold " },
  { line: 198, old: "text- ", new: "text-gold2 " },
  { line: 211, old: "bg- ", new: "bg-navy " },
  { line: 213, old: "text-\"", new: "text-gold\"" },
  { line: 247, old: "bg- ", new: "bg-gold " },
  { line: 247, old: "bg- ", new: "bg-gold2 " },
  { line: 340, old: "border-\"", new: "border-line\"" },
  { line: 368, old: "border- ", new: "border-line " },
  { line: 376, old: "border- ", new: "border-line " },
  { line: 386, old: "border- ", new: "border-line " },
  { line: 396, old: "border- ", new: "border-line " },
  { line: 412, old: "border- ", new: "border-line " },
  { line: 412, old: "border- ", new: "border-navy " },
  { line: 416, old: "border- ", new: "border-line " },
  { line: 416, old: "border- ", new: "border-navy " },
  { line: 420, old: "border- ", new: "border-line " },
  { line: 420, old: "border- ", new: "border-navy " },
  { line: 424, old: "border- ", new: "border-line " },
  { line: 424, old: "border- ", new: "border-navy " },
  { line: 428, old: "border- ", new: "border-line " },
  { line: 428, old: "border- ", new: "border-navy " },
  { line: 432, old: "border- ", new: "border-line " },
  { line: 432, old: "border- ", new: "border-navy " },
  { line: 436, old: "border- ", new: "border-line " },
  { line: 436, old: "border- ", new: "border-navy " },
  { line: 440, old: "border- ", new: "border-line " },
  { line: 440, old: "border- ", new: "border-navy " },
  { line: 444, old: "border- ", new: "border-line " },
  { line: 444, old: "border- ", new: "border-navy " },
  { line: 448, old: "border- ", new: "border-line " },
  { line: 448, old: "border- ", new: "border-navy " },
  { line: 452, old: "border- ", new: "border-line " },
  { line: 452, old: "border- ", new: "border-navy " },
  { line: 456, old: "border- ", new: "border-line " },
  { line: 456, old: "border- ", new: "border-navy " },
  { line: 470, old: "border- ", new: "border-line " },
  { line: 497, old: "border- ", new: "border-line " },
  { line: 513, old: "border- ", new: "border-line " },
  { line: 513, old: "border-\"", new: "border-navy\"" },
  { line: 517, old: "border- ", new: "border-line " },
  { line: 517, old: "border-\"", new: "border-navy\"" },
  { line: 521, old: "border- ", new: "border-line " },
  { line: 521, old: "border-\"", new: "border-navy\"" },
  { line: 525, old: "border- ", new: "border-line " },
  { line: 525, old: "border-\"", new: "border-navy\"" },
  { line: 529, old: "border- ", new: "border-line " },
  { line: 529, old: "border-\"", new: "border-navy\"" },
  { line: 533, old: "border- ", new: "border-line " },
  { line: 533, old: "border-\"", new: "border-navy\"" },
  { line: 537, old: "border- ", new: "border-line " },
  { line: 537, old: "border-\"", new: "border-navy\"" },
  { line: 541, old: "border- ", new: "border-line " },
  { line: 541, old: "border-\"", new: "border-navy\"" },
  { line: 551, old: "border- ", new: "border-line " },
  { line: 558, old: "bg- ", new: "bg-navy " },
  { line: 558, old: "border- ", new: "border-navy " },
  { line: 558, old: "bg-\"", new: "bg-navy2\"" },
  { line: 562, old: "border- ", new: "border-line " },
  { line: 562, old: "border-\"", new: "border-navy\"" },
  { line: 566, old: "border- ", new: "border-line " },
  { line: 566, old: "border-\"", new: "border-navy\"" },
  { line: 570, old: "border- ", new: "border-line " },
  { line: 570, old: "border-\"", new: "border-navy\"" },
  { line: 574, old: "border- ", new: "border-line " },
  { line: 574, old: "border-\"", new: "border-navy\"" },
  { line: 578, old: "border- ", new: "border-line " },
  { line: 578, old: "border-\"", new: "border-navy\"" },
  { line: 582, old: "border- ", new: "border-line " },
  { line: 582, old: "border-\"", new: "border-navy\"" },
  { line: 586, old: "border- ", new: "border-line " },
  { line: 586, old: "border-\"", new: "border-navy\"" },
  { line: 590, old: "border- ", new: "border-line " },
  { line: 590, old: "border-\"", new: "border-navy\"" },
  { line: 595, old: "border- ", new: "border-line " },
  { line: 595, old: "border- ", new: "border-navy " },
  { line: 610, old: "border- ", new: "border-line " },
  { line: 610, old: "border-\"", new: "border-navy\"" },
  { line: 614, old: "border- ", new: "border-line " },
  { line: 614, old: "border-\"", new: "border-navy\"" },
  { line: 618, old: "border- ", new: "border-line " },
  { line: 618, old: "border-\"", new: "border-navy\"" },
  { line: 622, old: "border- ", new: "border-line " },
  { line: 622, old: "border-\"", new: "border-navy\"" },
  { line: 626, old: "border- ", new: "border-line " },
  { line: 626, old: "border-\"", new: "border-navy\"" },
  { line: 641, old: "border- ", new: "border-line " },
  { line: 658, old: "border- ", new: "border-line " },
  { line: 675, old: "border- ", new: "border-line " },
  { line: 692, old: "border- ", new: "border-line " },
  { line: 709, old: "border- ", new: "border-line " },
  { line: 735, old: "border- ", new: "border-line " },
  { line: 745, old: "bg- ", new: "bg-navy " },
  { line: 749, old: "border- ", new: "border-line " },
  { line: 759, old: "bg- ", new: "bg-navy " },
  { line: 763, old: "border- ", new: "border-line " },
  { line: 788, old: "border- ", new: "border-line " },
  { line: 1094, old: "bg- ", new: "bg-navy " },
  { line: 1094, old: "bg- ", new: "bg-navy2 " },
  { line: 1138, old: "bg- ", new: "bg-navy " },
  { line: 1138, old: "text- ", new: "text-gold " },
  { line: 1139, old: "border- ", new: "border-navy " },
  { line: 1152, old: "text-\"", new: "text-gold\"" },
  { line: 1175, old: "text- ", new: "text-gold " },
  { line: 1229, old: "bg- ", new: "bg-navy " },
  { line: 1258, old: "bg-\"", new: "bg-navy\"" },
  { line: 1283, old: "bg-\"", new: "bg-gold\"" },
  { line: 1346, old: "bg- ", new: "bg-navy " },
  { line: 1346, old: "bg- ", new: "bg-navy2 " },
  { line: 1846, old: "bg- ", new: "bg-navy " },
  { line: 1867, old: "bg- ", new: "bg-navy " },
  { line: 1899, old: "bg- ", new: "bg-navy " },
  { line: 1974, old: "bg- ", new: "bg-navy " },
  { line: 2000, old: "bg- ", new: "bg-gold2 " },
  { line: 2003, old: "bg- ", new: "bg-navy " },
  { line: 2003, old: "bg- ", new: "bg-navy2 " },
  { line: 2027, old: "border-\"", new: "border-navy\"" },
  { line: 2069, old: "bg- ", new: "bg-navy " }
];

let lines = html.split('\n');
for (const r of replacements) {
  let idx = r.line - 1;
  if (lines[idx]) {
    lines[idx] = lines[idx].replace(r.old, r.new);
  }
}

fs.writeFileSync('index.html', lines.join('\n'));
console.log('Fixed index.html classes!');
