import React from 'react';
import { Flag, Quote } from 'lucide-react';
import { useSignature } from '../../context/SignatureContext';
import { BannerConfig, SloganConfig } from '../../types/signature';

const CAMPAIGNS = [
  { title: 'Salon & événements', campaign: 'Actualités RAGT', url: '/assets/bannieres/046805_BD.jpg' },
  { title: 'Innovation variétale', campaign: 'Génétique & performance', url: '/assets/bannieres/046806_BD.jpg' },
  { title: 'Recrutement', campaign: 'Rejoignez RAGT Semences', url: '/assets/bannieres/046807_BD.jpg' }
];

export const CampaignPanel: React.FC = () => {
  const { state, updateState, showToast } = useSignature();
  const { banner, slogan, visibility } = state;
  const updateBanner = (patch: Partial<BannerConfig>) => updateState((prev) => ({ ...prev, banner: { ...prev.banner, ...patch } }));
  const updateSlogan = (patch: Partial<SloganConfig>) => updateState((prev) => ({ ...prev, slogan: { ...prev.slogan, ...patch } }));
  const campaignEnabled = visibility.banner && banner.enabled && Boolean(banner.campaignName);

  return <div className="space-y-5 p-4 text-slate-800 dark:text-slate-200">
    <section className="space-y-3 rounded-xl border border-slate-200 bg-white p-3.5 text-xs dark:border-slate-700 dark:bg-slate-800">
      <div className="flex items-start justify-between gap-3"><div><h3 className="flex items-center gap-1.5 text-sm font-bold uppercase tracking-wide text-[#0C3866] dark:text-amber-400"><Flag className="h-4 w-4 text-[#F7BD00]" /> Campagnes</h3><p className="mt-0.5 text-xs text-slate-500">Un bandeau pleine largeur, limité à 90 px de haut.</p></div><button type="button" onClick={() => updateState((prev) => ({ ...prev, visibility: { ...prev.visibility, banner: !campaignEnabled }, banner: { ...prev.banner, enabled: !campaignEnabled } }))} className={`rounded-lg border px-2.5 py-1.5 text-[11px] font-bold ${campaignEnabled ? 'border-emerald-300 bg-emerald-50 text-emerald-800' : 'border-slate-200 text-slate-600'}`}>{campaignEnabled ? 'Affichée' : 'Masquée'}</button></div>
      <div className="grid grid-cols-3 gap-2">{CAMPAIGNS.map((item) => <button key={item.title} type="button" onClick={() => { updateBanner({ title: item.title, campaignName: item.campaign, altText: item.title, imageUrl: item.url, enabled: true, position: 'bottom', width: state.layout.dimensions.totalWidth, height: 90, maintainRatio: false, startDate: '', endDate: '' }); updateState((prev) => ({ ...prev, visibility: { ...prev.visibility, banner: true } })); showToast(`Campagne « ${item.title} » appliquée`, 'success'); }} className={`rounded-lg border p-1.5 text-left ${banner.imageUrl === item.url && banner.campaignName ? 'border-[#0C3866] ring-2 ring-[#0C3866]/20' : 'border-slate-200 hover:border-[#0C3866] dark:border-slate-700'}`}><img src={item.url} alt="" className="mb-1 h-12 w-full rounded object-cover"/><span className="block truncate text-[10px] font-bold">{item.title}</span></button>)}</div>
      <div className="grid grid-cols-2 gap-2"><label><span className="mb-1 block text-[11px] font-semibold">Lien au clic</span><input value={banner.linkUrl || ''} onChange={(event) => updateBanner({ linkUrl: event.target.value })} placeholder="https://…" className="w-full rounded border border-slate-200 px-2 py-1.5 text-xs dark:border-slate-700 dark:bg-slate-900"/></label><label><span className="mb-1 block text-[11px] font-semibold">Hauteur (20–90 px)</span><input type="number" min="20" max="90" value={Math.min(90, banner.height)} onChange={(event) => updateBanner({ height: Math.min(90, Math.max(20, Number(event.target.value) || 20)), maintainRatio: false })} className="w-full rounded border border-slate-200 px-2 py-1.5 text-xs dark:border-slate-700 dark:bg-slate-900"/></label></div>
      <div className="grid grid-cols-2 gap-2"><label><span className="mb-1 block text-[11px] font-semibold">Début</span><input type="date" value={banner.startDate || ''} onChange={(event) => updateBanner({ startDate: event.target.value })} className="w-full rounded border border-slate-200 px-2 py-1.5 text-xs dark:border-slate-700 dark:bg-slate-900"/></label><label><span className="mb-1 block text-[11px] font-semibold">Fin</span><input type="date" min={banner.startDate || undefined} value={banner.endDate || ''} onChange={(event) => updateBanner({ endDate: event.target.value })} className="w-full rounded border border-slate-200 px-2 py-1.5 text-xs dark:border-slate-700 dark:bg-slate-900"/></label></div>
    </section>
    <section className="space-y-3 rounded-xl border border-slate-200 bg-white p-3.5 text-xs dark:border-slate-700 dark:bg-slate-800"><div className="flex items-center justify-between"><h3 className="flex items-center gap-1.5 text-sm font-bold text-[#0C3866] dark:text-amber-400"><Quote className="h-4 w-4 text-[#F7BD00]"/>Slogan</h3><button type="button" onClick={() => updateState((prev) => ({ ...prev, visibility: { ...prev.visibility, slogan: !prev.visibility.slogan }, slogan: { ...prev.slogan, enabled: !prev.visibility.slogan } }))} className="text-[11px] font-bold text-[#0C3866] dark:text-amber-400">{visibility.slogan && slogan.enabled ? 'Masquer' : 'Afficher'}</button></div><textarea value={slogan.text} onChange={(event) => updateSlogan({ text: event.target.value })} rows={2} className="w-full rounded-lg border border-slate-200 bg-slate-50 px-2.5 py-2 text-xs dark:border-slate-700 dark:bg-slate-900"/><div className="grid grid-cols-3 gap-2"><label><span className="mb-1 block text-[10px] font-semibold">Taille</span><input type="number" min="9" max="16" value={slogan.fontSize} onChange={(event) => updateSlogan({ fontSize: Number(event.target.value) || 11 })} className="w-full rounded border border-slate-200 px-2 py-1 dark:border-slate-700 dark:bg-slate-900"/></label><label><span className="mb-1 block text-[10px] font-semibold">Couleur</span><input type="color" aria-label="Couleur du slogan" value={slogan.color} onChange={(event) => updateSlogan({ color: event.target.value })} className="h-7 w-full rounded border border-slate-200"/></label><label><span className="mb-1 block text-[10px] font-semibold">Alignement</span><select value={slogan.align} onChange={(event) => updateSlogan({ align: event.target.value as SloganConfig['align'] })} className="w-full rounded border border-slate-200 px-1 py-1 dark:border-slate-700 dark:bg-slate-900"><option value="left">Gauche</option><option value="center">Centre</option><option value="right">Droite</option></select></label></div></section>
  </div>;
};
